- name: build wheels of binary Python package {{ item }} # noqa 301
  shell:
    cmd: |
      pip3 wheel -w '{{ wheels_dir }}' \
        --extra-index-url {{ pip_extra_index_url }} \
        -c "{{ wheels_dir }}/upper-constraints.txt" \
        "{{ item }}"
    executable: /bin/bash
  environment:
    NPY_NUM_BUILD_JOBS: "{{ ansible_processor_vcpus }}"
    GRPC_PYTHON_BUILD_EXT_COMPILER_JOBS: "{{ ansible_processor_vcpus }}"

- name: get list of wheel files matchin {{ item }}
  find:
    path: "{{ wheels_dir }}"
    patterns: "{{ item | regex_replace('.=.*', '') }}*.whl"
    file_type: file
  register: wheel_files

- name: get filename of latest {{ item }} wheel
  set_fact:
    wheel_file: "{{ wheel_files.files | sort(attribute='mtime') | last }}"

- name: install {{ item }} Python package
  become: yes
  pip:
    name: "{{ wheel_file.path }}"
