- name: run auditwheel repair on wheels
  shell:
    cmd: "auditwheel repair -w {{ wheels_dir }} {{ item }}"
    chdir: "{{ wheels_dir }}"
  with_fileglob:
    - "{{ wheels_dir }}/tensorflow*.whl"
    - "{{ wheels_dir }}/h5py-3.2*.whl"

- name: drop non-manylinux wheels
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "{{ wheels_dir }}/tensorflow*linux_aarch64.whl"
    - "{{ wheels_dir }}/h5py-3.2*linux_aarch64.whl"
