- name: run auditwheel repair on wheels
  shell:
    cmd: "auditwheel repair {{ item }}"
    chdir: "{{ wheels_dir }}"
  with_fileglob:
    - "{{ wheels_dir }}/tensorflow*.whl"
    - "{{ wheels_dir }}/h5py-3.2*.whl"

- name: copy manylinux wheels into wheels
  copy:
    src: "{{ item }}"
    dest: "{{ wheels_dir }}"
    mode: 0666
    remote_src: true
  with_fileglob:
    - "{{ wheels_dir }}/wheelhouse/*.whl"

- name: drop non-manylinux wheels
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "{{ wheels_dir }}/tensorflow*linux_aarch64.whl"
    - "{{ wheels_dir }}/h5py-3.2*linux_aarch64.whl"

- name: drop wheelhouse dir
  file:
    path: "{{ wheels_dir }}/wheelhouse/"
    state: absent
