- hosts: localhost
  vars_files:
    ../vars/vars.yml

  tasks:
    - name: initialize job
      include_role:
        name: ldcg-manylinux-tensorflow
        tasks_from: init.yml

    - name: go through each TensorFlow version
      include_role:
        name: tensorflow
        tasks_from: loop.yml
      loop: "{{ versions | dict2items }}"
      loop_control:
        loop_var: tf_ver
      when: tf_ver.key in to_be_built

    - name: do publishing stuff
      include_role:
        name: ldcg-manylinux-tensorflow
        tasks_from: publish.yml
