- hosts: localhost
  vars_files:
    ../vars/vars-tfio.yml

  tasks:
    - name: create output wheels directory
      file:
        path: "{{ wheels_dir }}"
        state: directory
        mode: 0755

    - name: go through each TensorFlow IO version
      include_role:
        name: tensorflow-io
        tasks_from: loop.yml
      loop: "{{ tfio_versions | dict2items }}"
      loop_control:
        loop_var: tfio_ver
      when: tfio_ver.key in to_be_built

    - name: copy wheels for cache upload
      copy:
        src: "{{ wheels_dir }}"
        dest: "{{ build_dir }}/cache_upload"
        mode: 0644

    - name: prepare wheels for cache
      include_role:
        name: linaro
        tasks_from: publish-wheels-cache.yml
      vars:
        wheels_dir: "{{ build_dir }}/cache_upload"
