- block:
    - name: fetch tensorflow {{ tensorflow_version }} source
      get_url:
        url: "https://github.com/tensorflow/tensorflow/archive/v{{ tensorflow_version }}.tar.gz"
        dest: "{{ build_dir }}/tensorflow-{{ tensorflow_version }}.tar.gz"
        mode: 0600

    - name: unpack tensorflow {{ tensorflow_version }} source
      unarchive:
        src: "{{ build_dir }}/tensorflow-{{ tensorflow_version }}.tar.gz"
        dest: "{{ build_dir }}/"
        remote_src: true

    - name: copy configure script
      copy:
        src: "files/configure_tensorflow"
        dest: "{{ build_dir }}/tensorflow-{{ tensorflow_version }}/configure_tensorflow"
        mode: 0400

    - name: drop Python 2.7 deps
      lineinfile:
        regexp: "^.*'{{ item }} >=.*$"
        state: absent
        path: "{{ build_dir }}/tensorflow-{{ tensorflow_version }}/tensorflow/tools/pip_package/setup.py"
      loop:
        - "functools32"
        - "enum34"
        - "backports.weakref"
  when: tensorflow_version != 'git'

- block:
    - name: fetch tensorflow from git
      git:
        repo: "https://github.com/tensorflow/tensorflow.git"  # noqa 401
        dest: "{{ build_dir }}/tensorflow-{{ tensorflow_version }}/"
        depth: 1
        recursive: true
        force: true

    - name: copy configure script
      copy:
        src: "files/configure_tensorflow-git"
        dest: "{{ build_dir }}/tensorflow-{{ tensorflow_version }}/configure_tensorflow"
        mode: 0400
  when: tensorflow_version == 'git'
